version: "3.8"



services:
  database:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    container_name: database
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - $DATABASE_LOCAL_PORT:$DATABASE_DOCKER_PORT
    volumes:
    #  - ./volume:/data/db
      - db_volume:/var/lib/postgresql/data
    networks:
      - app-networks

  backend:
    depends_on:
      - database
    image: ehmboup/flaskapp:v4.0.0 
    restart: unless-stopped
    container_name: ehflaskapp
    env_file: ./.env
    ports:
      - $APP_LOCAL_PORT:$APP_DOCKER_PORT
    environment:
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_NAME=$DATABASE_NAME
    networks:
      - app-networks

networks:
  app-networks:

volumes:
  db_volume:
